Hw04 auth
VolodymyrVorona/nodejs-homework-template pull request #3
Opened 2021-09-09 09:27 UTC by VolodymyrVorona

2021-09-10 04:57 UTC, Danil44 requested changes

2021-09-10 04:57 UTC, Danil44 commented on app.js
> +//LB8yMB7DrPiK9URG
Що це?

2021-09-10 04:57 UTC, Danil44 commented on controllers/contacts/removeById.js
> +    // return res.status(404).json({
Не повинно бути закоментованого коду

2021-09-11 09:27 UTC, VolodymyrVorona commented on controllers/contacts/removeById.js
> +    // return res.status(404).json({
Видалив закоментованi рядки.

2021-09-11 11:11 UTC, Danil44 approved these changes

2021-09-14 15:47 UTC, merged